In [6]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [38]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 20))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 3)
print("Range Array:\n", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1,9)
print("Linspace Array:\n", linspace_arr)

# Random array
random_arr = np.random.rand(3, 9)  # Uniform distribution
print("Random Array:\n", random_arr)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array:
 [0 3 6 9]
Linspace Array:
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
Random Array:
 [[0.0970209  0.67203573 0.38065281 0.33538653 0.91600335 0.01164081
  0.24337681 0.18364228 0.17449691]
 [0.80559399 0.31524002 0.08893922 0.1126271  0.18083342 0.9864169
  0.16868618 0.78820561 0.34320771]
 [0.7590471  0.07902765 0.90385531 0.81810365 0.97535011 0.56703321
  0.60818829 0.47177904 0.596395  ]]


In [32]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1.0, 2.9, 3.8], [4.9, 5.0, 6.9],[2.9,9.0,8.0]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

Shape: (3, 3)
Size: 9
Data Type: float64
Number of Dimensions: 2


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * 8)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [ 8 16 24]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933


### Some assignment problems

In [10]:
# Assignment 1
'''
Create an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.
Then reshape it to a (9, 2) array and take its transpose. 
Find the locations where all elements are greater than the mean of the array and print it
'''

'\nCreate an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.\nThen reshape it to a (9, 2) array and take its transpose. \nFind the locations where all elements are greater than the mean of the array and print it\n'

In [102]:
# TODO
ran = np.random.rand(3, 6)
print ("Random 3,6 generated array:\n",ran)
arr=np.array([0, 0, 2, 4, 5, 3])
ran=ran+arr
ran=ran.reshape((9, 2))
ran=ran.T
print("Array after all operations:\n",ran)
mean=np.mean(ran)
print("mean of array:\n",mean)
locations = [(row, col) for row in range(ran.shape[0]) for col in range(ran.shape[1]) if ran[row, col] > mean]
print("Final locations in (row,col) format:\n",locations)

Random 3,6 generated array:
 [[0.81969347 0.94524519 0.40589305 0.28277176 0.98007519 0.6369102 ]
 [0.66646691 0.8415175  0.31596033 0.63575168 0.99227554 0.06482726]
 [0.93518632 0.12020171 0.67676628 0.64906557 0.69752964 0.55183541]]
Array after all operations:
 [[0.81969347 2.40589305 5.98007519 0.66646691 2.31596033 5.99227554
  0.93518632 2.67676628 5.69752964]
 [0.94524519 4.28277176 3.6369102  0.8415175  4.63575168 3.06482726
  0.12020171 4.64906557 3.55183541]]
mean of array:
 2.956554055413993
Final locations in (row,col) format:
 [(0, 2), (0, 5), (0, 8), (1, 1), (1, 2), (1, 4), (1, 5), (1, 7), (1, 8)]


In [91]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''

'\nCreate an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation\n(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)\n'

In [134]:
# TODO
# Hint use np.random.poisson
a=22
arr=np.random.poisson(a,20)
mean=np.mean(arr)
arr=arr-mean
std=np.std(arr)
arr=arr/std
print(arr)

[-0.88261207 -1.11186196 -0.4241123   0.26363737  0.49288726  0.26363737
  1.8683866   0.03438748 -2.4873613  -2.02886152 -0.4241123   0.49288726
  0.26363737  0.95138704  0.72213715 -0.19486241  0.03438748  0.95138704
  0.49288726  0.72213715]
